/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#1D68FF',
        'primary-dark': '#002F8E',
        'primary-light': '#DBE6FF',
        'primary-subtle': '#82ABFD',
        black: '#121218',
        'gray-0': '#FFFFFF',
        'gray-100': '#EDF0F3',
        'gray-200': '#C5C8CB',
        'gray-300': '#9DA0A3',
        'gray-400': '#75787B',
        'gray-500': '#4D5053',
        'gray-600': '#25282B',
        danger: '#ED5151',
        warning: '#FF732D',
        caution: '#FFCC00',
        'safe-light': '#A1F68E',
        safe: '#247CFF',
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', fontWeight: '600' }],
        h1: ['32px', { lineHeight: '1.125', fontWeight: '600' }],
        'h2-semibold': ['24px', { lineHeight: '1.5', fontWeight: '600' }],
        'h2-medium': ['24px', { lineHeight: '1.5', fontWeight: '500' }],
        h3: ['22px', { lineHeight: '1.636', fontWeight: '400' }],
        'body-1-regular': ['20px', { lineHeight: '1.8', fontWeight: '400' }],
        'body-1-light': ['20px', { lineHeight: '1.8', fontWeight: '300' }],
        'body-2': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'caption-1': ['15px', { lineHeight: '1.5', fontWeight: '600' }],
        'caption-2': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
      },
      fontFamily: {
        sans: [
          'Pretendard Variable',
          'Pretendard',
          '-apple-system',
          'BlinkMacSystemFont',
          'system-ui',
          'Roboto',
          '"Helvetica Neue"',
          '"Segoe UI"',
          '"Apple SD Gothic Neo"',
          '"Noto Sans KR"',
          '"Malgun Gothic"',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
};
